In [1]:
import pandas as pd
import numpy as np

In [2]:
matches = pd.read_csv('ipl/matches.csv')

In [3]:
matches.shape

(636, 18)

In [4]:
matches.head()

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN

In [5]:
pd.unique(matches['season'])

array([2017, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016],
      dtype=int64)

In [6]:
pd.unique(matches['winner'])

array(['Sunrisers Hyderabad', 'Rising Pune Supergiant',
       'Kolkata Knight Riders', 'Kings XI Punjab',
       'Royal Challengers Bangalore', 'Mumbai Indians',
       'Delhi Daredevils', 'Gujarat Lions', 'Chennai Super Kings',
       'Rajasthan Royals', 'Deccan Chargers', 'Pune Warriors',
       'Kochi Tuskers Kerala', nan, 'Rising Pune Supergiants'],
      dtype=object)

In [7]:
pd.value_counts(matches['winner'])

Mumbai Indians                 92
Chennai Super Kings            79
Kolkata Knight Riders          77
Royal Challengers Bangalore    73
Kings XI Punjab                70
Rajasthan Royals               63
Delhi Daredevils               62
Sunrisers Hyderabad            42
Deccan Chargers                29
Gujarat Lions                  13
Pune Warriors                  12
Rising Pune Supergiant         10
Kochi Tuskers Kerala            6
Rising Pune Supergiants         5
Name: winner, dtype: int64

In [8]:
pd.value_counts(matches['toss_winner'])

Mumbai Indians                 85
Kolkata Knight Riders          78
Delhi Daredevils               72
Royal Challengers Bangalore    70
Kings XI Punjab                68
Chennai Super Kings            66
Rajasthan Royals               63
Deccan Chargers                43
Sunrisers Hyderabad            35
Pune Warriors                  20
Gujarat Lions                  15
Kochi Tuskers Kerala            8
Rising Pune Supergiants         7
Rising Pune Supergiant          6
Name: toss_winner, dtype: int64

In [18]:
# pd.value_counts(matches['player_of_match'])

In [27]:
matches[matches['player_of_match'] == 'MS Dhoni'][:10][['team1','team2','player_of_match','venue']].reset_index().drop(columns=['index'])

,team1,team2,player_of_match,venue
0,Sunrisers Hyderabad,Rising Pune Supergiant,MS Dhoni,Maharashtra Cricket Association Stadium
1,Chennai Super Kings,Royal Challengers Bangalore,MS Dhoni,M Chinnaswamy Stadium
2,Delhi Daredevils,Chennai Super Kings,MS Dhoni,Feroz Shah Kotla
3,Chennai Super Kings,Deccan Chargers,MS Dhoni,Buffalo Park
4,Chennai Super Kings,Kolkata Knight Riders,MS Dhoni,Eden Gardens
5,Kings XI Punjab,Chennai Super Kings,MS Dhoni,Himachal Pradesh Cricket Association Stadium
6,Chennai Super Kings,Delhi Daredevils,MS Dhoni,"MA Chidambaram Stadium, Chepauk"
7,Chennai Super Kings,Mumbai Indians,MS Dhoni,M Chinnaswamy Stadium
8,Sunrisers Hyderabad,Chennai Super Kings,MS Dhoni,"MA Chidambaram Stadium, Chepauk"
9,Chennai Super Kings,Pune Warriors,MS Dhoni,Subrata Roy Sahara Stadium

In [28]:
matches[(matches['player_of_match'] == 'MS Dhoni') & (matches['toss_decision'] == 'field') & (matches['toss_winner'] == 'Chennai Super Kings')]

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
86,87,2008,Delhi,2008-05-08,Delhi Daredevils,Chennai Super Kings,Chennai Super Kings,field,normal,0,Chennai Super Kings,0,4,MS Dhoni,Feroz Shah Kotla,Aleem Dar,RB Tiffin,NaN
227,228,2010,Dharamsala,2010-04-18,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,field,normal,0,Chennai Super Kings,0,6,MS Dhoni,Himachal Pradesh Cricket Association Stadium,BF Bowden,AM Saheba,NaN
509,510,2014,Bangalore,2014-05-24,Royal Challengers Bangalore,Chennai Super Kings,Chennai Super Kings,field,normal,0,Chennai Super Kings,0,8,MS Dhoni,M Chinnaswamy Stadium,AK Chaudhary,NJ Llong,NaN

In [32]:
matches.drop_duplicates('season',keep='last')[['season','winner']]

     season                 winner
58     2017         Mumbai Indians
116    2008       Rajasthan Royals
173    2009        Deccan Chargers
233    2010    Chennai Super Kings
306    2011    Chennai Super Kings
380    2012  Kolkata Knight Riders
456    2013         Mumbai Indians
516    2014  Kolkata Knight Riders
575    2015         Mumbai Indians
635    2016    Sunrisers Hyderabad